// Generated by SolidPython 1.1.3 on 2026-03-31 17:10:39
$fn = 80;


union() {
	translate(v = [-1.5811388300841898, -1.5811388300841898, 0]) {
		cylinder(h = 1.0000000000, r = 0.2000000000);
	}
	translate(v = [4.743416490252569, 1.58113883008419, 0]) {
		cylinder(h = 1.0000000000, r = 0.2000000000);
	}
	translate(v = [-4.743416490252569, 1.581138830084189, 0]) {
		cylinder(h = 1.0000000000, r = 0.2000000000);
	}
	translate(v = [1.58113883008419, -1.5811388300841895, 0]) {
		cylinder(h = 1.0000000000, r = 0.2000000000);
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
import numpy as np
import math
import subprocess
from solid import *
from solid.utils import *

# --------------------------------------------------
# INPUT PATH
# --------------------------------------------------

POINTS = np.array([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [0.0, 0.0],
], dtype=float)

FOLLOWER_RADIUS = 0.2
CYLINDER_HEIGHT = 1.0
TARGET_SCALE = 5.0
NUM_SAMPLED_POINTS = len(POINTS)

SCAD_FILENAME = "groove_debug.scad"
STL_FILENAME = "groove_debug.stl"

# --------------------------------------------------
# HELPERS
# --------------------------------------------------

def rotation_matrix(theta):
    c = math.cos(theta)
    s = math.sin(theta)
    return np.array([
        [c, -s],
        [s,  c]
    ], dtype=float)

def normalize_and_scale_points(points, target_scale=1.0):
    pts = np.array(points, dtype=float)

    # Center the points
    pts = pts - pts.mean(axis=0)

    # Find the largest radius from origin
    radii = np.linalg.norm(pts, axis=1)
    max_radius = np.max(radii)

    # Avoid division by zero
    if max_radius < 1e-12:
        return pts

    # Scale so the maximum radius becomes target_scale
    pts = pts / max_radius * target_scale
    return pts

# --------------------------------------------------
# PREPARE PATH
# --------------------------------------------------

pts = normalize_and_scale_points(POINTS, TARGET_SCALE)
d_theta = 2 * math.pi / NUM_SAMPLED_POINTS

# --------------------------------------------------
# BUILD DEBUG GROOVE AS CYLINDERS
# --------------------------------------------------

cylinders = []

for i in range(NUM_SAMPLED_POINTS):
    theta = i * d_theta

    # Desired follower location in world frame
    Q = pts[i]

    # Groove point in cam frame
    C = rotation_matrix(-theta) @ Q
    x, y = C

    cyl = translate([x, y, 0])(
        cylinder(r=FOLLOWER_RADIUS, h=CYLINDER_HEIGHT)
    )

    cylinders.append(cyl)

groove_debug = union()(*cylinders)

# --------------------------------------------------
# WRITE SCAD
# --------------------------------------------------

scad_render_to_file(
    groove_debug,
    SCAD_FILENAME,
    file_header='$fn = 80;'
)

print(f"Wrote {SCAD_FILENAME}")

# --------------------------------------------------
# CONVERT SCAD -> STL
# --------------------------------------------------

try:
    subprocess.run(
        ["openscad", "-o", STL_FILENAME, SCAD_FILENAME],
        check=True
    )
    print(f"Wrote {STL_FILENAME}")
except FileNotFoundError:
    print("Could not find the 'openscad' command.")
    print("Install OpenSCAD and make sure the 'openscad' CLI is available in your terminal PATH.")
except subprocess.CalledProcessError as e:
    print("OpenSCAD failed while converting SCAD to STL.")
    print(e) 
 
************************************************/
